[tool.black]
    line-length = 99
    target-version = ['py38']
    include = '\.py$'
    force-exclude = '''
    /(
        redbot\/vendored
    )/
    '''

[tool.isort]
    profile = "black"
    line_length = 99
    combine_as_imports = true
    skip_glob = [
        "redbot/vendored/*"
    ]
    filter_files = true
