################################################
#          SENSITIVE SECTION WARNING           #
################################################
# Any edits of any of the exported names       #
# may result in a breaking change.             #
# Ensure no names are removed without warning. #
################################################

# DEP-WARN: Check this *every* discord.py update
from discord.ext.commands import (
    ArgumentParsingError as ArgumentParsingError,
    AutoShardedBot as AutoShardedBot,
    BadArgument as BadArgument,
    BadBoolArgument as BadBoolArgument,
    BadColourArgument as BadColourArgument,
    BadInviteArgument as BadInviteArgument,
    BadUnionArgument as BadUnionArgument,
    Bot as Bot,
    BotMissingAnyRole as BotMissingAnyRole,
    BotMissingRole as BotMissingRole,
    BucketType as BucketType,
    CategoryChannelConverter as CategoryChannelConverter,
    ChannelNotFound as ChannelNotFound,
    ChannelNotReadable as ChannelNotReadable,
    CheckAnyFailure as CheckAnyFailure,
    CheckFailure as CheckFailure,
    CogMeta as CogMeta,
    ColorConverter as ColorConverter,
    ColourConverter as ColourConverter,
    CommandError as CommandError,
    CommandInvokeError as CommandInvokeError,
    CommandNotFound as CommandNotFound,
    CommandOnCooldown as CommandOnCooldown,
    CommandRegistrationError as CommandRegistrationError,
    ConversionError as ConversionError,
    Converter as Converter,
    Cooldown as Cooldown,
    CooldownMapping as CooldownMapping,
    DefaultHelpCommand as DefaultHelpCommand,
    DisabledCommand as DisabledCommand,
    EmojiConverter as EmojiConverter,
    EmojiNotFound as EmojiNotFound,
    ExpectedClosingQuoteError as ExpectedClosingQuoteError,
    ExtensionAlreadyLoaded as ExtensionAlreadyLoaded,
    ExtensionError as ExtensionError,
    ExtensionFailed as ExtensionFailed,
    ExtensionNotFound as ExtensionNotFound,
    ExtensionNotLoaded as ExtensionNotLoaded,
    GameConverter as GameConverter,
    Greedy as Greedy,
    HelpCommand as HelpCommand,
    IDConverter as IDConverter,
    InvalidEndOfQuotedStringError as InvalidEndOfQuotedStringError,
    InviteConverter as InviteConverter,
    MaxConcurrency as MaxConcurrency,
    MaxConcurrencyReached as MaxConcurrencyReached,
    MemberConverter as MemberConverter,
    MemberNotFound as MemberNotFound,
    MessageConverter as MessageConverter,
    MessageNotFound as MessageNotFound,
    MinimalHelpCommand as MinimalHelpCommand,
    MissingAnyRole as MissingAnyRole,
    MissingPermissions as MissingPermissions,
    MissingRequiredArgument as MissingRequiredArgument,
    MissingRole as MissingRole,
    NoEntryPointError as NoEntryPointError,
    NoPrivateMessage as NoPrivateMessage,
    NotOwner as NotOwner,
    NSFWChannelRequired as NSFWChannelRequired,
    Paginator as Paginator,
    PartialEmojiConversionFailure as PartialEmojiConversionFailure,
    PartialEmojiConverter as PartialEmojiConverter,
    PrivateMessageOnly as PrivateMessageOnly,
    RoleConverter as RoleConverter,
    RoleNotFound as RoleNotFound,
    TextChannelConverter as TextChannelConverter,
    TooManyArguments as TooManyArguments,
    UnexpectedQuoteError as UnexpectedQuoteError,
    UserConverter as UserConverter,
    UserInputError as UserInputError,
    UserNotFound as UserNotFound,
    VoiceChannelConverter as VoiceChannelConverter,
    bot_has_guild_permissions as bot_has_guild_permissions,
    check_any as check_any,
    clean_content as clean_content,
    max_concurrency as max_concurrency,
)

from ._dpy_reimplements import (
    after_invoke as after_invoke,
    before_invoke as before_invoke,
    bot_has_any_role as bot_has_any_role,
    bot_has_role as bot_has_role,
    check as check,
    cooldown as cooldown,
    dm_only as dm_only,
    guild_only as guild_only,
    has_any_role as has_any_role,
    has_role as has_role,
    is_nsfw as is_nsfw,
    when_mentioned as when_mentioned,
    when_mentioned_or as when_mentioned_or,
)
from .commands import (
    RESERVED_COMMAND_NAMES as RESERVED_COMMAND_NAMES,
    Cog as Cog,
    CogCommandMixin as CogCommandMixin,
    CogGroupMixin as CogGroupMixin,
    CogMixin as CogMixin,
    Command as Command,
    Group as Group,
    GroupMixin as GroupMixin,
    RedUnhandledAPI as RedUnhandledAPI,
    command as command,
    group as group,
)
from .context import Context as Context, DMContext as DMContext, GuildContext as GuildContext
from .converter import (
    DictConverter as DictConverter,
    GuildConverter as GuildConverter,
    Literal as Literal,
    NoParseOptional as NoParseOptional,
    TimedeltaConverter as TimedeltaConverter,
    UserInputOptional as UserInputOptional,
    get_dict_converter as get_dict_converter,
    get_timedelta_converter as get_timedelta_converter,
    parse_timedelta as parse_timedelta,
)
from .errors import (
    ArgParserFailure as ArgParserFailure,
    BotMissingPermissions as BotMissingPermissions,
    ConversionFailure as ConversionFailure,
    UserFeedbackCheckFailure as UserFeedbackCheckFailure,
)
from .help import (
    HelpSettings as HelpSettings,
    RedHelpFormatter as RedHelpFormatter,
    red_help as red_help,
)
from .requires import (
    DM_PERMS as DM_PERMS,
    CheckPredicate as CheckPredicate,
    GlobalPermissionModel as GlobalPermissionModel,
    GuildPermissionModel as GuildPermissionModel,
    PermissionModel as PermissionModel,
    PermState as PermState,
    PrivilegeLevel as PrivilegeLevel,
    Requires as Requires,
    admin as admin,
    admin_or_permissions as admin_or_permissions,
    bot_has_permissions as bot_has_permissions,
    bot_in_a_guild as bot_in_a_guild,
    guildowner as guildowner,
    guildowner_or_permissions as guildowner_or_permissions,
    has_guild_permissions as has_guild_permissions,
    has_permissions as has_permissions,
    is_owner as is_owner,
    mod as mod,
    mod_or_permissions as mod_or_permissions,
    permissions_check as permissions_check,
)

__all__ = (
    # discord.ext.commands
    "ArgumentParsingError",
    "AutoShardedBot",
    "BadArgument",
    "BadBoolArgument",
    "BadColourArgument",
    "BadInviteArgument",
    "BadUnionArgument",
    "Bot",
    "BotMissingAnyRole",
    "BotMissingRole",
    "BucketType",
    "CategoryChannelConverter",
    "ChannelNotFound",
    "ChannelNotReadable",
    "CheckAnyFailure",
    "CheckFailure",
    "CogMeta",
    "ColorConverter",
    "ColourConverter",
    "CommandError",
    "CommandInvokeError",
    "CommandNotFound",
    "CommandOnCooldown",
    "CommandRegistrationError",
    "ConversionError",
    "Converter",
    "Cooldown",
    "CooldownMapping",
    "DefaultHelpCommand",
    "DisabledCommand",
    "EmojiConverter",
    "EmojiNotFound",
    "ExpectedClosingQuoteError",
    "ExtensionAlreadyLoaded",
    "ExtensionError",
    "ExtensionFailed",
    "ExtensionNotFound",
    "ExtensionNotLoaded",
    "GameConverter",
    "Greedy",
    "HelpCommand",
    "IDConverter",
    "InvalidEndOfQuotedStringError",
    "InviteConverter",
    "MaxConcurrency",
    "MaxConcurrencyReached",
    "MemberConverter",
    "MemberNotFound",
    "MessageConverter",
    "MessageNotFound",
    "MinimalHelpCommand",
    "MissingAnyRole",
    "MissingPermissions",
    "MissingRequiredArgument",
    "MissingRole",
    "NoEntryPointError",
    "NoPrivateMessage",
    "NotOwner",
    "NSFWChannelRequired",
    "Paginator",
    "PartialEmojiConversionFailure",
    "PartialEmojiConverter",
    "PrivateMessageOnly",
    "RoleConverter",
    "RoleNotFound",
    "TextChannelConverter",
    "TooManyArguments",
    "UnexpectedQuoteError",
    "UserConverter",
    "UserInputError",
    "UserNotFound",
    "VoiceChannelConverter",
    "bot_has_guild_permissions",
    "check_any",
    "clean_content",
    "max_concurrency",
    # ._dpy_reimplements
    "after_invoke",
    "before_invoke",
    "bot_has_any_role",
    "bot_has_role",
    "check",
    "cooldown",
    "dm_only",
    "guild_only",
    "has_any_role",
    "has_role",
    "is_nsfw",
    "when_mentioned",
    "when_mentioned_or",
    # .commands
    "RESERVED_COMMAND_NAMES",
    "Cog",
    "CogCommandMixin",
    "CogGroupMixin",
    "CogMixin",
    "Command",
    "Group",
    "GroupMixin",
    "RedUnhandledAPI",
    "command",
    "group",
    # .context
    "Context",
    "DMContext",
    "GuildContext",
    # .converter
    "DictConverter",
    "GuildConverter",
    "Literal",
    "NoParseOptional",
    "TimedeltaConverter",
    "UserInputOptional",
    "get_dict_converter",
    "get_timedelta_converter",
    "parse_timedelta",
    # .errors
    "ArgParserFailure",
    "BotMissingPermissions",
    "ConversionFailure",
    "UserFeedbackCheckFailure",
    # .help
    "HelpSettings",
    "RedHelpFormatter",
    "red_help",
    # .requires
    "DM_PERMS",
    "CheckPredicate",
    "GlobalPermissionModel",
    "GuildPermissionModel",
    "PermissionModel",
    "PermState",
    "PrivilegeLevel",
    "Requires",
    "admin",
    "admin_or_permissions",
    "bot_has_permissions",
    "bot_in_a_guild",
    "guildowner",
    "guildowner_or_permissions",
    "has_guild_permissions",
    "has_permissions",
    "is_owner",
    "mod",
    "mod_or_permissions",
    "permissions_check",
)
