name: Lint Python
on:
  pull_request:
  push:
  repository_dispatch:
    types:
      - dispatched_test

env:
  ref: ${{ github.event.client_payload.ref || '' }}

jobs:
  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: "python -m pip install flake8==3.9.0"
        name: Install Flake8
      - run: "python -m flake8 . --count --show-source"
        name: Flake8 Linting
